### ISSUE TITLE
ssh access for frontend-project based project

### ISSUE THREAD

**Issue by badrange** [wunderio/silta-images#7]
We have a frontend-project where we need to add psql/postgresql support to the shell container (to do debugging etc in postgresql), and I noticed this comment in values.yaml:

> Note: Shell only works when the base image wunderio/silta-node is used!
https://github.com/wunderio/frontend-project-k8s/blob/master/charts/frontend/values.yaml#L256

So I tried to configure our shell Docker to use that image, but circleci deployment failed with a timeout. Does this work with the node16 image/is it in use in other frontend projects?

**Comment by Jancis** [comment]
That comment needs an update, `wunderio/silta-node` was on dockerhub and there might be some breaking changes since. You could try using one of images from `eu.gcr.io/silta-images/node`, but since You mention `shell`, it sounds more like drupal chart where it does not apply. If you need to add cli tools, you can just add `apk add` commands to `Dockerfile` in Your project.
Your vertical expert should be able to help with this

**Comment by badrange** [comment]
Now I'm confused, but also happy.

I added this issue months ago when I gave up trying to get a shell container to work in our `frontend-project` based project, and after reading your comment I resurrected that old branch, rebased it on master and pushed to github. Voila, I was able to ssh into the project and use psql to connect to the database.

So I'll close this issue as things seem to work as expected.
